name: Votifier-bungee
main: com.vexsoftware.votifier.Votifier
version: maven-version-number
description: A plugin that gets notified when votes are made for the server on toplists.
author: 'blakeman8192, Kramer, Chelcy'